import { Outfit, Poppins} from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"], weight: ["400","500","600","700"]
});

const poppins = Poppins({
  subsets: ["latin"], weight: ["400","500","600","700"]
});

export const metadata = {
  title: "Portfolio-Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.className} ${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
